export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const FETCH_PHOTOS_ERROR = "FETCH_PHOTOS_ERROR";
export const PHOTO_SELECTED = 'PHOTO_SELECTED';
export const PHOTO_DESELECTED = 'PHOTO_DESELECTED';
export const SERCH_TERM_UPDATE = 'SERCH_TERM_UPDATE';
